/* This file is generated by scripts/generate-projects.mjs. Do not edit by hand. */
import type { Project } from "./projects";

export const projects: Project[] = [
  {
    "slug": "bitts-and-pieces",
    "title": "Bitts and Pieces",
    "subtitle": "Track 1 | Bitts and Pieces",
    "year": 2024,
    "role": "Producer, Engineer, Mixing Engineer, Mastering Engineer",
    "tags": [
      "Bitty",
      "Detroit",
      "Hip-hop",
      "Rap",
      "Trap",
      "WANYEH"
    ],
    "blurb": "Detroit-style club banger with heavy low-end and sharp drum programming.",
    "tone": [
      "#0f0f12",
      "#3b2d2a"
    ],
    "deliverables": [
      "Full instrumental production",
      "Arrangement",
      "Final mix and master"
    ],
    "credits": [
      "Bitty — Artist",
      "WANYEH — Artist",
      "Anthony Dake — Producer/Engineer",
      "Mixed by Anthony Dake",
      "Mastered by Anthony Dake"
    ],
    "narrative": [
      "Produced, tracked, mixed, and mastered in Logic Pro X, inspired by Detroit-style beats.",
      "Built for club systems with a punchy kick and a tight, forward vocal pocket."
    ],
    "links": [
      {
        "label": "Apple Music",
        "href": "https://music.apple.com/us/song/bitts-and-pieces-feat-wanyeh/1745381882"
      },
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/1IsudjdAu9xKZObUgRIR0R"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=c_5nM0kKoig"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/bitts-and-pieces.jpg",
        "alt": "Bitts and Pieces cover art",
        "title": "Bitts and Pieces"
      }
    ]
  },
  {
    "slug": "cruisin",
    "title": "Cruisin",
    "subtitle": "Track 2 | Eight Track (Side A)",
    "year": 2024,
    "role": "Producer, Engineer, Mixing Engineer, Mastering Engineer",
    "tags": [
      "Hip-hop",
      "KJ The Cool Nerd",
      "Rap",
      "Trap"
    ],
    "blurb": "Dark trap banger with a driving low end and focused vocal pocket.",
    "tone": [
      "#0b0b0f",
      "#24232c"
    ],
    "deliverables": [
      "Full instrumental production",
      "Arrangement",
      "Final mix and master"
    ],
    "credits": [
      "KJ The Cool Nerd — Artist",
      "Anthony Dake — Producer/Engineer",
      "Mixed by Anthony Dake",
      "Mastered by Anthony Dake"
    ],
    "narrative": [
      "Produced, tracked, mixed, and mastered in Logic Pro X, inspired by dark trap textures.",
      "Built around a steady groove and restrained synths to keep the track moody and cinematic."
    ],
    "links": [
      {
        "label": "Apple Music",
        "href": "https://music.apple.com/us/song/crusin/1768645695"
      },
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/5K3R4JMGVFi5JgsmGJy475"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=8Bd6yGuyaRQ"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/cruisin.jpg",
        "alt": "Cruisin cover art",
        "title": "Cruisin"
      }
    ]
  },
  {
    "slug": "dark-knight",
    "title": "Dark Knight",
    "subtitle": "Track 3 | Eight Track (Side A)",
    "year": 2024,
    "role": "Producer, Engineer, Mixing Engineer, Mastering Engineer",
    "tags": [
      "Hip-hop",
      "KJ The Cool Nerd",
      "Rap",
      "Trap",
      "WANYEH"
    ],
    "blurb": "Dark trap banger with heavy 808s and sharp, minimal synth lines.",
    "tone": [
      "#0b0b0f",
      "#24232c"
    ],
    "deliverables": [
      "Full instrumental production",
      "Arrangement",
      "Final mix and master"
    ],
    "credits": [
      "KJ The Cool Nerd — Artist",
      "WANYEH — Artist",
      "Anthony Dake — Producer/Engineer",
      "Mixed by Anthony Dake",
      "Mastered by Anthony Dake"
    ],
    "narrative": [
      "Produced, tracked, mixed, and mastered in Logic Pro X, inspired by dark trap textures.",
      "Built around a heavy low-end and tense atmosphere to keep the track aggressive and focused."
    ],
    "links": [
      {
        "label": "Apple Music",
        "href": "https://music.apple.com/us/song/dark-knight-feat-wanyeh/1768645696"
      },
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/1GLe4jR0vEucIYPiYLXnu4"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=_QfPY7PeSbQ"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/dark-knight.jpg",
        "alt": "Dark Knight cover art",
        "title": "Dark Knight"
      }
    ]
  },
  {
    "slug": "lazy-days",
    "title": "Lazy Days",
    "subtitle": "Track 1 | Finn and Jake",
    "year": 2023,
    "role": "Engineer",
    "tags": [
      "Bitty",
      "Boom-bap",
      "Hip-hop",
      "KJ The Cool Nerd",
      "Rap",
      "Trap",
      "WANYEH"
    ],
    "blurb": "The start of the Columbus sound — built around the energy of the University District shows at Juniors Bar & Grill.",
    "tone": [
      "#141516",
      "#3b2c24"
    ],
    "deliverables": [
      "Engineering"
    ],
    "credits": [
      "Bitty — Artist",
      "WANYEH — Artist",
      "Anthony Dake — Engineer",
      "KJ The Cool Nerd — Producer"
    ],
    "narrative": [
      "Produced, tracked, mixed, and mastered on Ableton Live, inspired by classic hip-hop.",
      "Captured the early momentum of the scene with a boom-bap foundation and live-show energy."
    ],
    "links": [
      {
        "label": "Apple Music",
        "href": "https://music.apple.com/us/song/lazy-days/1720656018"
      },
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/2c4QYczlcjVqyim1P8kw3s"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=9IDW7HOz1sc"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/small-business.jpg",
        "alt": "Finn and Jake cover art",
        "title": "Lazy Days"
      }
    ]
  },
  {
    "slug": "repercussions",
    "title": "Repercussions",
    "subtitle": "Single | Bitty",
    "year": 2023,
    "role": "Producer, Songwriter, Mixing Engineer, Mastering Engineer",
    "tags": [
      "Bitty",
      "BittyOTW",
      "Chill",
      "Intimate",
      "R&B",
      "Rap",
      "Synths"
    ],
    "blurb": "First of a couple singles with Bitty, built across a few sessions at Otterbein University.",
    "tone": [
      "#5a3a1f",
      "#a06f3a"
    ],
    "deliverables": [
      "Full instrumental production",
      "Programming",
      "Arrangement",
      "Tracking",
      "Final mix and master"
    ],
    "credits": [
      "Bitty — Artist",
      "Anthony Dake — Producer, Songwriter",
      "Mixed by Anthony Dake",
      "Mastered by Anthony Dake"
    ],
    "narrative": [
      "Developed over a handful of sessions at Otterbein University, tracked and finished in Logic Pro X.",
      "Long talks with Judy about topline melodic writing helped frame the record so it held momentum and the right emotional feel."
    ],
    "links": [
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/4fxUvrFR0yJSXg5CuJpb6Z"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=MUdrD0wVsJ8"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/repercussions.jpg",
        "alt": "Repercussions single cover art",
        "title": "Repercussions"
      }
    ]
  },
  {
    "slug": "small-business",
    "title": "Small Business",
    "subtitle": "Track 2 | Finn and Jake",
    "year": 2023,
    "role": "Producer, Engineer, Mixing Engineer, Mastering Engineer",
    "tags": [
      "Bitty",
      "Club",
      "Hip-hop",
      "KJ The Cool Nerd",
      "Rap",
      "Trap",
      "WANYEH"
    ],
    "blurb": "\"I've been up three days making plays\" — a snapshot of the University District shows at Juniors Bar & Grill.",
    "tone": [
      "#141516",
      "#3b2c24"
    ],
    "deliverables": [
      "Full instrumental production",
      "Drum programming",
      "Arrangement",
      "Final mix and master"
    ],
    "credits": [
      "Bitty — Artist",
      "WANYEH — Artist",
      "Anthony Dake — Producer/Engineer",
      "Mixed by Anthony Dake",
      "Mastered by Anthony Dake"
    ],
    "narrative": [
      "Produced, tracked, mixed, and mastered in Logic Pro X, leaning into classic hip-hop energy.",
      "Captured the momentum and memory of those University District shows while keeping the record club-ready."
    ],
    "links": [
      {
        "label": "Apple Music",
        "href": "https://music.apple.com/us/song/small-business/1720656019"
      },
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/7DGF2H2TtDbDeniGV1wRLk"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=SQU4NuenSCo"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/small-business.jpg",
        "alt": "Finn and Jake cover art",
        "title": "Small Business"
      }
    ]
  },
  {
    "slug": "missin-u",
    "title": "Missin U (feat. Riyah)",
    "subtitle": "Track 9 | Class Loser",
    "year": 2022,
    "role": "Producer, Writer, Engineer, Mixing/Mastering Engineer",
    "tags": [
      "Hip-hop",
      "KJ The Cool Nerd",
      "Neo-soul",
      "R&B",
      "Rap",
      "Riyah"
    ],
    "blurb": "One of the first tracks produced for KJ The Cool Nerd.",
    "tone": [
      "#0b0b0b",
      "#1f2937"
    ],
    "deliverables": [
      "Full instrumental production",
      "Drum programming",
      "Arrangement",
      "Final mix"
    ],
    "credits": [
      "KJ The Cool Nerd — Artist",
      "Riyah — Artist",
      "Anthony Dake — Production/Writing",
      "Mixed by Anthony Dake",
      "Mastered by Anthony Dake"
    ],
    "narrative": [
      "One of the sessions leading up to KJ The Cool Nerd’s album \"Class Loser\" (released February 24, 2022).",
      "Inspired by YouTube beats and young energy, produced, mixed, and mastered in Pro Tools at Studio F, Capital University."
    ],
    "links": [
      {
        "label": "Apple Music",
        "href": "https://music.apple.com/us/song/missin-u-feat-riyah/1607007135"
      },
      {
        "label": "Spotify",
        "href": "https://open.spotify.com/track/71yLH6PBReEAahASoGQnD5"
      },
      {
        "label": "YouTube",
        "href": "https://www.youtube.com/watch?v=Sqxoyx_LDYw"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/missin-u.jpg",
        "alt": "Studio session photo for Missin U",
        "title": "Missin U session"
      },
      {
        "kind": "audio",
        "provider": "spotify",
        "url": "https://open.spotify.com/embed/track/71yLH6PBReEAahASoGQnD5",
        "title": "Spotify",
        "height": 152
      },
      {
        "kind": "audio",
        "provider": "apple_music",
        "url": "https://embed.music.apple.com/us/song/missin-u-feat-riyah/1607007135",
        "title": "Apple Music",
        "height": 175
      },
      {
        "kind": "video",
        "provider": "youtube",
        "id": "Sqxoyx_LDYw",
        "title": "YouTube"
      }
    ]
  }
];
