/* This file is generated by scripts/generate-projects.mjs. Do not edit by hand. */
import type { Project } from "./projects";

export const projects: Project[] = [
  {
    "slug": "template",
    "title": "Template Placement",
    "subtitle": "Placeholder project description",
    "year": 2026,
    "role": "PRODUCTION/SONGWRITING",
    "tags": [
      "Placeholder"
    ],
    "blurb": "Placeholder summary for a placement. Replace with real context, roles, and outcomes.",
    "tone": [
      "#0f172a",
      "#1f2937"
    ],
    "deliverables": [
      "Placeholder deliverable",
      "Second deliverable"
    ],
    "credits": [
      "Artist: Placeholder",
      "Role: Production/ Songwriting"
    ],
    "narrative": [
      "Placeholder narrative point about the scope and creative approach.",
      "Placeholder narrative point about tools, timeline, and results."
    ],
    "links": [
      {
        "label": "Reference link",
        "href": "https://example.com"
      }
    ],
    "media": [
      {
        "kind": "image",
        "src": "/placements/template/placeholder.jpg",
        "alt": "Placeholder studio session",
        "title": "Template Image"
      }
    ]
  }
];
